import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp,writeFile,readFile,mkdir } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { Store,uid,roles } from '../server/store.mjs';
import { Runtime,stages } from '../server/runtime.mjs';
import { createApp } from '../server/app.mjs';
import { git,prepareWorkspace,allowedFile } from '../server/workspaces.mjs';
import { command } from '../server/process.mjs';
import { acquireServerLock } from '../server/lock.mjs';

async function fixture(){const dir=await mkdtemp(path.join(os.tmpdir(),'rain-company-test-'));return {dir,store:new Store(path.join(dir,'data'))};}
function project(store,changes={}){return store.put('project','company',{id:uid(),name:'Test project',goal:'Scoped goal',repository:'',stack:'',testCommand:'node --test',model:'',maxRuns:30,tokenBudget:300000,networkAccess:false,allowedPaths:['.'],assignments:[],...changes});}
function hire(store,role='po'){const c=store.list('candidate','company').find(c=>c.role===role);return store.put('employee','company',{...c,id:uid(),candidateId:c.id});}
const waitForIdle=async runtime=>{for(let n=0;runtime.active.size;n++){if(n>1000)throw new Error('Runtime never became idle');await new Promise(r=>setTimeout(r,10));}};

test('Git stdout remains separate from warnings and one server owns the database',async()=>{const {dir,store}=await fixture();const release=acquireServerLock(store.dir);assert.throws(()=>acquireServerLock(store.dir),/실행 중/);release();const second=acquireServerLock(store.dir);second();const result=await command(process.execPath,['-e','process.stdout.write("file.txt");process.stderr.write("warning: CRLF")'],dir);assert.equal(result.stdout,'file.txt');assert.equal(result.stderr,'warning: CRLF');store.close();});

test('empty company supports 11 roles and 33 candidates without a connected project',async()=>{const {store}=await fixture();assert.equal(roles.length,11);assert.equal(store.list('candidate','company').length,33);assert.equal(store.list('project','company').length,0);assert.ok(hire(store).id);store.close();});
test('project memories, messages, tasks, usage and prompts do not mix',async()=>{const {store}=await fixture();const a=project(store),b=project(store);const e=hire(store);store.put('memory',a.id,{id:uid(),text:'SECRET_FOR_PROJECT_A'});store.message(a.id,'대표','A message');store.put('task',a.id,{id:'a-task',title:'A only'});store.put('run',a.id,{id:uid(),status:'completed',usage:{last:{totalTokens:79}}});const r=new Runtime(store);assert.equal(store.list('message',b.id).length,0);assert.equal(r.usage(b.id).tokens,0);assert.throws(()=>store.require('task',b.id,'a-task'));assert.ok(!r.instructions(b.id,e).includes('SECRET_FOR_PROJECT_A'));assert.ok(r.instructions(a.id,e).includes('SECRET_FOR_PROJECT_A'));assert.throws(()=>r.employee(b.id,e.id));store.close();});
test('restart recovery preserves thread identity and completed checkpoints',async()=>{const {dir,store}=await fixture();const p=project(store);store.put('task',p.id,{id:'task',status:'running',checkpoints:{po:{status:'completed',runId:'r'}}});store.put('run',p.id,{id:'r',status:'running',threadId:'thread-resume-id'});store.close();const reopened=new Store(path.join(dir,'data'));reopened.recover();assert.equal(reopened.get('task',p.id,'task').status,'paused');assert.equal(reopened.get('task',p.id,'task').checkpoints.po.status,'completed');assert.equal(reopened.get('run',p.id,'r').threadId,'thread-resume-id');assert.equal(reopened.get('run',p.id,'r').status,'interrupted');reopened.close();});
test('run budgets include failed attempts and global stop persists',async()=>{const {dir,store}=await fixture();const p=project(store,{maxRuns:1});const r=new Runtime(store);store.put('run',p.id,{id:uid(),status:'failed'});assert.throws(()=>r.budget(p.id),/예산/);r.stopAll();store.close();const s=new Store(path.join(dir,'data'));assert.equal(s.get('settings','company','main').stopped,true);assert.throws(()=>new Runtime(s).budget('company'),/중지/);s.close();});
test('relative write allowlist rejects traversal, prefix confusion and credentials',()=>{assert.equal(allowedFile('src/app.ts',['src']),true);assert.equal(allowedFile('src-other/app.ts',['src']),false);assert.equal(allowedFile('../outside',['.']),false);assert.equal(allowedFile('C:/outside',['.']),false);assert.equal(allowedFile('.env.production',['.']),false);assert.equal(allowedFile('keys/service.pem',['.']),false);assert.equal(allowedFile('.env.example',['.']),true);});

test('HTTP authorization, CSRF protection, hiring and project scope access',async()=>{const {store}=await fixture();const runtime=new Runtime(store);const app=createApp(store,runtime);const server=app.listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));const base=`http://127.0.0.1:${server.address().port}`;try{
  assert.equal((await fetch(base+'/api/bootstrap')).status,401);
  assert.equal((await fetch(base+'/api/session',{headers:{Origin:'https://evil.example'}})).status,403);
  const s=await fetch(base+'/api/session');const cookie=s.headers.get('set-cookie').split(';')[0];const request=(url,method='GET',body)=>fetch(base+url,{method,headers:{cookie,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined});
  assert.equal((await request('/api/bootstrap')).status,200);
  const candidate=store.list('candidate','company')[0];assert.equal((await request(`/api/candidates/${candidate.id}/hire`,'POST',{})).status,201);assert.equal((await request(`/api/candidates/${candidate.id}/hire`,'POST',{})).status,409);
  const pa=await (await request('/api/projects','POST',{name:'A'})).json();const pb=await (await request('/api/projects','POST',{name:'B'})).json();
  const t=await (await request(`/api/scopes/${pa.id}/tasks`,'POST',{title:'Only A',description:'Project A task'})).json();
  assert.equal((await (await request(`/api/scopes/${pb.id}`)).json()).tasks.length,0);
  assert.equal((await request(`/api/scopes/${pb.id}/tasks/${t.id}/start`,'POST',{})).status,409);
  assert.equal((await request(`/api/projects`,'POST',{name:'bad',allowedPaths:['../other']})).status,400);
}finally{await new Promise(r=>server.close(r));store.close();}});

test('workspace snapshot preserves staged, unstaged and untracked source changes',async()=>{const {dir,store}=await fixture();const repo=path.join(dir,'original');await mkdir(repo);await git(repo,['init']);await git(repo,['config','user.name','Test']);await git(repo,['config','user.email','test@localhost']);await writeFile(path.join(repo,'file.txt'),'original\n');await git(repo,['add','.']);await git(repo,['commit','-m','baseline']);await writeFile(path.join(repo,'file.txt'),'staged\n');await git(repo,['add','.']);await writeFile(path.join(repo,'file.txt'),'unstaged\n');await writeFile(path.join(repo,'untracked.txt'),'notes\n');await writeFile(path.join(repo,'.env'),'PRIVATE_TOKEN=not-for-snapshot');
  const before=(await git(repo,['status','--porcelain'])).output;const p=project(store,{repository:repo});const t=store.put('task',p.id,{id:uid(),status:'queued'});const w=await prepareWorkspace(store,p,t,new AbortController().signal);
  assert.equal((await readFile(path.join(w.repo,'file.txt'),'utf8')).replace(/\r\n/g,'\n'),'unstaged\n');assert.equal(await readFile(path.join(w.repo,'untracked.txt'),'utf8'),'notes\n');await assert.rejects(readFile(path.join(w.repo,'.env')));assert.equal((await git(repo,['status','--porcelain'])).output,before);assert.equal((await git(repo,['diff','--cached'])).output.includes('+staged'),true);store.close();});

test('chat cancellation saves interrupted record and resumes the same scoped thread',async()=>{const {store}=await fixture();const p=project(store);const e=hire(store);store.patch('project','company',p.id,{assignments:[{employeeId:e.id,permission:'read'}]});let threadReceived;let calls=0;const runtime=new Runtime(store,{clientFactory:()=>({start:async()=>{},close(){},run:async options=>{threadReceived=options.threadId;options.onThread('persisted-thread');calls++;if(calls===1)return new Promise((resolve,reject)=>options.signal.addEventListener('abort',()=>reject(new Error('stopped')),{once:true}));options.onEvent({method:'item/completed',params:{item:{type:'agentMessage',text:'답변'}}});return {text:'답변',threadId:'persisted-thread',turnId:'t2',usage:{last:{totalTokens:5}}};}})});
  runtime.startChat(p.id,e,'첫 질문');while(!store.list('run',p.id)[0]?.threadId)await new Promise(r=>setTimeout(r,10));runtime.stopAll();await waitForIdle(runtime);assert.equal(store.list('run',p.id)[0].status,'interrupted');store.patch('settings','company','main',{stopped:false});runtime.startChat(p.id,e,'이어서');await waitForIdle(runtime);assert.equal(threadReceived,'persisted-thread');assert.equal(store.list('run',p.id)[1].status,'completed');store.close();});

test('pipeline resumes after failed role without replaying completed roles',async()=>{const {dir,store}=await fixture();const repo=path.join(dir,'repo');await mkdir(repo);await git(repo,['init']);await git(repo,['config','user.name','Test']);await git(repo,['config','user.email','test@localhost']);await writeFile(path.join(repo,'base.txt'),'baseline');await git(repo,['add','.']);await git(repo,['commit','-m','baseline']);const employees=stages.map(r=>hire(store,r));const p=project(store,{repository:repo,testCommand:'node -e "console.log(123)"',assignments:employees.map(e=>({employeeId:e.id,permission:['backend','frontend'].includes(e.role)?'write':'read'}))});const t=store.put('task',p.id,{id:uid(),title:'task',description:'small change',status:'queued',checkpoints:{}});const calls=[];let fail=true;
  const runtime=new Runtime(store,{clientFactory:()=>({start:async()=>{},close(){},run:async o=>{const role=Object.keys({po:1,cto:1,backend:1,frontend:1,qa:1}).find(r=>o.instructions.includes(`직무 ${roles.find(x=>x.id===r).name}입니다`));calls.push(role);o.onThread(`thread-${role}`);if(role==='frontend'&&fail){fail=false;throw new Error('transient failure');}if(['backend','frontend'].includes(role))await writeFile(path.join(o.cwd,role+'.txt'),role);const text=JSON.stringify({summary:role,handoff:'done',passed:true});o.onEvent({method:'item/completed',params:{item:{type:'agentMessage',text}}});return {text,threadId:`thread-${role}`,turnId:'turn',usage:{last:{totalTokens:12}}};}})});
  runtime.startTask(p.id,t.id);await waitForIdle(runtime);assert.equal(store.get('task',p.id,t.id).status,'blocked');runtime.startTask(p.id,t.id);await waitForIdle(runtime);const result=store.get('task',p.id,t.id);assert.equal(result.status,'review',result.error);assert.deepEqual(calls,['po','cto','backend','frontend','frontend','qa']);assert.equal(result.testResult.exitCode,0);assert.deepEqual(result.result.files,['backend.txt','frontend.txt']);store.close();});
