import { z } from 'zod';
import { uid, now, roles } from './store.mjs';
import { hash, syncExperiences, addFeedback } from './experience.mjs';

export const activityNames={briefing:'목표 설명·업무 지시',decision:'질문·의사결정',review:'결과물 검토',editing:'직접 코드·문서 수정',recovery:'오류·장애 수습',maintenance:'앱 설정·유지보수'};
const date=z.string().regex(/^\d{4}-\d{2}-\d{2}$/).refine(d=>!isNaN(Date.parse(d))&&new Date(d).toISOString().slice(0,10)===d,'올바른 날짜를 입력하세요.');
export const personalSettings=z.object({coordinatorId:z.string().default(''),technicalCoordinatorId:z.string().default(''),urgentTypes:z.array(z.enum(['security','data_loss','service_down','external','conflict','scope','info','failure'])).default([]),urgentKeywords:z.array(z.string().trim().min(2).max(100)).max(10).default([]),digestHour:z.number().int().min(0).max(23).default(18)}).strict();
export const experimentSchema=z.object({label:z.string().trim().min(1).max(160),startDate:date,days:z.union([z.literal(7),z.literal(14)]),targetMinutes:z.number().positive().max(1440).default(30),timezone:z.enum(['Asia/Seoul','UTC']).default('Asia/Seoul')}).strict();
export const timeBody=z.object({category:z.enum(Object.keys(activityNames)),target:z.enum(['project','company_tool']),date,minutes:z.number().min(0).max(10080),taskId:z.string().default(''),goalId:z.string().default(''),cause:z.enum(['normal','error','requirements_change']).default('normal'),note:z.string().max(3000).default('')}).strict();
export const timerBody=timeBody.omit({date:true,minutes:true});
export const localDate=(iso,zone='Asia/Seoul')=>new Intl.DateTimeFormat('sv-SE',{timeZone:zone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(iso));
export const addDays=(d,n)=>new Date(Date.parse(d+'T00:00:00Z')+n*86400000).toISOString().slice(0,10);
export function projectPeople(store,scope){return store.require('project','company',scope).assignments.map(a=>({...store.require('employee','company',a.employeeId),permission:a.permission}));}
export function liaison(store,p,technical=false){const id=technical?p.personal?.technicalCoordinatorId:p.personal?.coordinatorId;return id?projectPeople(store,p.id).find(e=>e.id===id):projectPeople(store,p.id).find(e=>e.role===(technical?'cto':'po'));}
export function configurePersonal(store,scope,input){if(store.list('job',scope).some(j=>j.status==='running'))throw new Error('이 프로젝트의 실행이 끝난 뒤 창구를 변경하세요.');const body=personalSettings.parse(input),people=projectPeople(store,scope);if(body.coordinatorId&&!people.some(e=>e.id===body.coordinatorId))throw new Error('대표 창구는 이 프로젝트에 배정된 직원이어야 합니다.');if(body.technicalCoordinatorId&&!people.some(e=>e.id===body.technicalCoordinatorId&&e.role==='cto'))throw new Error('기술 조율은 프로젝트의 CTO를 선택하세요.');const p=store.require('project','company',scope);return store.patch('project','company',scope,{personal:{...p.personal,...body}});}
export function syncGoals(store,p){for(const g of p.operation?.objectives||[]){const old=store.get('goalDefinition',p.id,g.id),digest=hash({text:g.text,acceptance:g.acceptance});if(old?.versions.at(-1).hash===digest)continue;store.put('goalDefinition',p.id,{id:g.id,projectId:p.id,current:(old?.current||0)+1,versions:[...(old?.versions||[]),{version:(old?.current||0)+1,text:g.text,acceptance:g.acceptance,hash:digest,createdAt:now()}]});}}
export function goalSnapshot(store,scope,goalId){if(!goalId)return null;const p=store.require('project','company',scope);syncGoals(store,p);const g=store.require('goalDefinition',scope,goalId);return {id:goalId,...g.versions.at(-1)};}
const normalize=s=>String(s).normalize('NFKC').toLowerCase().replace(/\s+/g,' ').trim();
export function recordSignal(store,scope,{id=uid(),kind,topic,text,taskId,runId,decisionId,employeeId,goalId}){if(store.get('operationSignal',scope,id))return store.get('operationSignal',scope,id);return store.put('operationSignal',scope,{id,projectId:scope,kind,topic:topic||hash(normalize(text)),text,taskId,runId,decisionId,employeeId,goalId,createdAt:now()});}
export function enrichDecision(store,scope,d,detail={}){
  const p=store.require('project','company',scope),t=store.get('task',scope,d.taskId);const body={question:detail.question||d.reason,why:detail.why||d.reason,recommendation:detail.recommendation||'필요한 근거를 확인한 뒤 답변하세요.',recommendationReason:detail.recommendationReason||'직원이 추천안을 아직 제출하지 않았습니다.',alternatives:detail.alternatives||d.options||[],affectedTaskIds:detail.affectedTaskIds||[d.taskId].filter(Boolean),preplannedApproval:detail.preplannedApproval??['external','scope'].includes(d.type)};
  const urgent=(p.personal?.urgentTypes||[]).includes(d.type)||(p.personal?.urgentKeywords||[]).some(k=>normalize(body.question+' '+body.why).includes(normalize(k)));
  const updated={...d,...body,urgent,groupKey:hash([d.type,normalize(body.question),body.alternatives,body.recommendation]),taskTitle:t?.title};
  store.put('decision',scope,updated);recordSignal(store,scope,{id:'decision:'+d.id,kind:'question',text:body.question,topic:updated.groupKey,taskId:d.taskId,decisionId:d.id});
  if(urgent&&!store.get('notification',scope,'decision:'+d.id))store.put('notification',scope,{id:'decision:'+d.id,decisionId:d.id,kind:'urgent',text:body.question,createdAt:now(),read:false});return updated;
}
export function decisionInbox(store,scope){const pending=store.list('decision',scope).filter(d=>d.status==='pending'&&['waiting_info','waiting_approval'].includes(store.get('task',scope,d.taskId)?.status));const tasks=store.list('task',scope);const groups=new Map();for(const original of pending){const d=original.groupKey?original:enrichDecision(store,scope,original);const key=d.groupKey;const group=groups.get(key)||{...d,id:key,decisionIds:[],affectedTaskIds:[],occurrences:0};group.decisionIds.push(d.id);group.affectedTaskIds=[...new Set([...group.affectedTaskIds,...d.affectedTaskIds])];group.urgent=group.urgent||d.urgent;group.occurrences++;groups.set(key,group);}return [...groups.values()].map(d=>({...d,canContinue:tasks.filter(t=>t.status==='queued'&&!d.affectedTaskIds.includes(t.id)&&!t.dependsOn?.some(id=>d.affectedTaskIds.includes(id)||!['review','completed'].includes(tasks.find(x=>x.id===id)?.status))).map(t=>({id:t.id,title:t.title})),affectedTasks:d.affectedTaskIds.map(id=>tasks.find(t=>t.id===id)).filter(Boolean).map(t=>({id:t.id,title:t.title,status:t.status}))})).sort((a,b)=>Number(b.urgent)-Number(a.urgent)||a.createdAt.localeCompare(b.createdAt));}
function validateTimeLinks(store,scope,b){if(scope!=='company')store.require('project','company',scope);else if(b.target==='project')throw new Error('프로젝트를 선택하세요.');if(b.taskId){const t=store.require('task',scope,b.taskId);if(b.goalId&&t.goalId!==b.goalId)throw new Error('업무와 목표가 다른 프로젝트 기록입니다.');}if(b.goalId)store.require('goalDefinition',scope,b.goalId);}
export function addTime(store,scope,input,extra={}){const b=timeBody.parse(input);validateTimeLinks(store,scope,b);return store.put('intervention',scope,{id:uid(),projectId:scope,...b,method:'manual',createdAt:now(),...extra});}
export function startTimer(store,scope,input,at=now()){const b=timerBody.parse(input);validateTimeLinks(store,scope,b);const running=store.get('timer','company','main');if(running?.status==='running')throw new Error('이미 시작한 타이머를 종료하세요. 시간 중복을 방지합니다.');return store.put('timer','company',{id:'main',scope,...b,status:'running',startedAt:at});}
export function stopTimer(store,scope,{minutes,note}={},at=now()){
  const t=store.require('timer','company','main');if(t.scope!==scope||t.status!=='running')throw new Error('이 범위에서 실행 중인 타이머가 없습니다.');const elapsed=(Date.parse(at)-Date.parse(t.startedAt))/60000;if(elapsed<0||!Number.isFinite(elapsed))throw new Error('시각을 확인한 뒤 사후 시간으로 기록하세요.');
  const zone=scope==='company'?'Asia/Seoul':currentExperiment(store,scope)?.timezone||'Asia/Seoul';const {id,status,scope:_,startedAt,updatedAt,...body}=t;
  // Explicit timer time spans days; split at each local midnight for period totals.
  const parts=[];let cursor=Date.parse(t.startedAt),end=Date.parse(at);while(cursor<end){let next=Math.min(end,cursor+86400000);const day=localDate(cursor,zone);if(localDate(next-1,zone)!==day){let lo=cursor,hi=next;while(hi-lo>1){const mid=Math.floor((lo+hi)/2);if(localDate(mid,zone)===day)lo=mid;else hi=mid;}next=hi;}parts.push({date:day,minutes:(next-cursor)/60000});cursor=next;}
  if(!parts.length)parts.push({date:localDate(at,zone),minutes:0});const actual=minutes===undefined?elapsed:z.number().min(0).max(10080).parse(minutes);
  return store.transaction(()=>{const entries=parts.map(p=>addTime(store,scope,{...body,date:p.date,minutes:elapsed?actual*p.minutes/elapsed:actual,note:note??body.note},{method:'timer',timerStartedAt:startedAt,timerStoppedAt:at,rawElapsedMinutes:elapsed,adjusted:minutes!==undefined}));store.patch('timer','company','main',{status:'stopped',stoppedAt:at,entryIds:entries.map(e=>e.id)});return entries;});
}
export function currentExperiment(store,scope){const p=store.require('project','company',scope);return p.personal?.experimentId?store.get('experiment',scope,p.personal.experimentId):null;}
export function createExperiment(store,scope,input){const body=experimentSchema.parse(input),p=store.require('project','company',scope);const e=store.put('experiment',scope,{id:uid(),...body,endDate:addDays(body.startDate,body.days-1),createdAt:now()});store.patch('project','company',scope,{personal:{...p.personal,experimentId:e.id}});return e;}
export function scopeRules(store,scope,employeeId){if(scope==='company')return '';return store.list('operationImprovement',scope).filter(i=>i.status==='applied'&&(!i.employeeId||i.employeeId===employeeId)).map(i=>`프로젝트 운영 지침 ${i.id} v${i.version}: ${i.rule}`).join('\n');}
export function improvementCandidates(store,scope){const signals=store.list('operationSignal',scope),groups=new Map();for(const s of signals){const key=s.kind+':'+s.topic;groups.set(key,[...(groups.get(key)||[]),s]);}for(const [key,items] of groups){if(items.length<2)continue;const id=hash(key),old=store.get('operationImprovement',scope,id);if(old){if(old.sourceIds.length!==items.length)store.patch('operationImprovement',scope,id,{sourceIds:items.map(s=>s.id)});continue;}store.put('operationImprovement',scope,{id,kind:items[0].kind,topic:items[0].topic,sourceIds:items.map(s=>s.id),title:items[0].text.slice(0,180),rule:'',expectedEffect:'같은 질문 또는 오류 수습을 줄일 수 있는지 관찰합니다. 아직 효과 미측정.',status:'candidate',version:0,history:[],createdAt:now()});}return store.list('operationImprovement',scope);}
export function applyImprovement(store,scope,id,input){const b=z.object({rule:z.string().trim().min(1).max(4000),expectedEffect:z.string().min(1).max(2000),employeeId:z.string().default(''),active:z.boolean()}).strict().parse(input);const i=store.require('operationImprovement',scope,id);if(b.employeeId&&!projectPeople(store,scope).some(p=>p.id===b.employeeId))throw new Error('이 프로젝트 직원을 선택하세요.');const version=i.version+1,entry={...b,version,createdAt:now()};return store.patch('operationImprovement',scope,id,{...b,version,status:b.active?'applied':'disabled',appliedAt:b.active?now():i.appliedAt,history:[...i.history,entry]});}
export function recordReview(store,scope,task,input){const body=z.object({outcome:z.enum(['accepted','changes']),cause:z.enum(['none','error','requirements_change']).default('none'),notes:z.string().max(4000).default(''),technicalIntervention:z.enum(['none','yes','unknown']).default('unknown')}).strict().parse(input);const r=store.put('resultReview',scope,{id:uid(),taskId:task.id,goalId:task.goalId,...body,createdAt:now()});recordSignal(store,scope,{id:'review:'+r.id,kind:body.outcome==='changes'?'rework':'feedback',text:body.notes||body.outcome,taskId:task.id,goalId:task.goalId});if(body.notes){syncExperiences(store,scope);const qa=store.list('run',scope).filter(x=>x.taskId===task.id&&x.role==='qa').at(-1);if(qa&&store.get('experience',scope,'run:'+qa.id)){const feedback=addFeedback(store,scope,'run:'+qa.id,{text:body.notes,humanVerified:body.outcome==='accepted'},'ceo');store.patch('resultReview',scope,r.id,{feedbackId:feedback.id});}}return store.require('resultReview',scope,r.id);}
export function goalGroups(store,scope){const tasks=store.list('task',scope).filter(t=>t.purpose==='work');return store.list('goalDefinition',scope).flatMap(g=>g.versions.map(v=>{const linked=tasks.filter(t=>t.goalId===g.id&&t.goalSnapshot?.version===v.version);const effective=linked.filter(t=>t.status!=='reopened');const allVerified=!!effective.length&&effective.every(t=>['review','completed'].includes(t.status)&&t.verification==='passed'&&t.evidence);const accepted=store.list('goalAssessment',scope).filter(a=>a.goalId===g.id&&a.version===v.version).at(-1);return {id:g.id,...v,current:g.current===v.version,tasks:linked.map(t=>({id:t.id,title:t.title,status:t.status,verification:t.verification,evidence:t.evidence,result:t.result,teamPlan:t.teamPlan})),allVerified,accepted:!!accepted&&accepted.taskSet===hash(linked.map(t=>[t.id,t.evidence]))&&allVerified&&linked.every(t=>['completed','reopened'].includes(t.status)),assessment:accepted};}));}
export function assessGoal(store,scope,id,input){const b=z.object({version:z.number().int().positive(),notes:z.string().trim().min(1).max(4000)}).strict().parse(input);const g=goalGroups(store,scope).find(g=>g.id===id&&g.version===b.version);if(!g?.allVerified||g.tasks.some(t=>!['completed','reopened'].includes(t.status)))throw new Error('목표에 연결된 결과를 검증하고 대표 검토를 마친 뒤 완료 기준을 확인하세요.');return store.put('goalAssessment',scope,{id:uid(),goalId:id,...b,criteria:g.acceptance,taskSet:hash(g.tasks.map(t=>[t.id,t.evidence])),createdAt:now(),confirmedBy:'ceo'});}
export const baselineBody=z.object({date,taskType:z.string().min(1).max(100),size:z.enum(['small','medium','large']),title:z.string().min(1).max(200),acceptance:z.string().min(1).max(5000),minutes:z.number().min(0).max(10080).nullable(),tokens:z.number().int().min(0).nullable(),cost:z.number().min(0).nullable(),currency:z.enum(['USD','KRW']).default('USD'),costBasis:z.enum(['measured','estimated','unavailable']).default('unavailable'),model:z.string().max(100).default(''),goalId:z.string().default(''),notes:z.string().max(3000).default('')}).strict();
export function addBaseline(store,scope,input){const b=baselineBody.parse(input);if(b.goalId)store.require('goalDefinition',scope,b.goalId);if(b.cost!==null&&b.costBasis==='unavailable')throw new Error('비용의 실측/추정 여부를 선택하세요.');return store.put('baseline',scope,{id:uid(),...b,createdAt:now()});}
function ratio(n,d){return {numerator:n,denominator:d,value:d?n/d:null};}
export function personalMetrics(store,scope,at=now()){
  const experiment=scope==='company'?null:currentExperiment(store,scope),zone=experiment?.timezone||'Asia/Seoul';const today=localDate(at,zone);const range=experiment?{start:experiment.startDate,end:experiment.endDate}:{start:today,end:today};const inDate=d=>d>=range.start&&d<=range.end;
  const own=(scope==='company'?[{id:'company'},...store.list('project','company')].flatMap(p=>store.list('intervention',p.id)):store.list('intervention',scope)).filter(e=>!e.voided&&inDate(e.date));const maintenance=scope==='company'?[]:store.list('intervention','company').filter(e=>!e.voided&&inDate(e.date));const entries=[...own,...maintenance];const coverage=store.list('timeCoverage',scope).filter(x=>inDate(x.date));
  const known=entries.length>0||coverage.some(x=>x.complete);const sum=items=>items.reduce((n,e)=>n+e.minutes,0);const days=[];for(let d=range.start;d<=range.end;d=addDays(d,1)){const items=entries.filter(e=>e.date===d),covered=coverage.some(c=>c.date===d&&c.complete);days.push({date:d,measuredMinutes:items.length||covered?sum(items):null,coverageComplete:covered,categories:Object.fromEntries(Object.keys(activityNames).map(c=>{const list=items.filter(i=>i.category===c);return [c,list.length||covered?sum(list):null];})),overTarget:items.length?Math.max(0,sum(items)-(experiment?.targetMinutes||30)):covered?0:null});}
  const tasks=scope==='company'?[]:store.list('task',scope).filter(t=>t.purpose==='work');const dated=items=>items.filter(x=>x.createdAt&&inDate(localDate(x.createdAt,zone)));const reviews=dated(store.list('resultReview',scope)).filter(r=>tasks.some(t=>t.id===r.taskId));const first=new Map();for(const r of store.list('resultReview',scope).filter(r=>tasks.some(t=>t.id===r.taskId)))if(!first.has(r.taskId))first.set(r.taskId,r);const firstIn=[...first.values()].filter(r=>reviews.some(x=>x.id===r.id));const reopen=dated(store.list('rework',scope));const goals=scope==='company'?[]:goalGroups(store,scope);const accepted=goals.filter(g=>g.accepted&&g.assessment&&inDate(localDate(g.assessment.createdAt,zone)));
  const problems=tasks.filter(t=>(t.verificationHistory?.some(v=>v.exitCode!==0)||t.reworkCause==='error')&&t.verification==='passed'&&t.finishedAt&&inDate(localDate(t.finishedAt,zone))).map(t=>{const r=store.list('resultReview',scope).filter(r=>r.taskId===t.id).at(-1);const direct=entries.some(e=>e.taskId===t.id&&['editing','recovery'].includes(e.category)&&e.minutes>0);return {taskId:t.id,technicalIntervention:direct?'yes':r?.technicalIntervention||'unknown'};});
  const acceptedCohort=tasks.filter(t=>t.acceptedAt&&inDate(localDate(t.acceptedAt,zone)));const reopenedCohort=new Set(reopen.filter(r=>r.cause==='error'&&r.wasCompleted&&acceptedCohort.some(t=>t.id===r.parentTaskId)).map(r=>r.parentTaskId));
  const runs=dated(scope==='company'?[{id:'company'},...store.list('project','company')].flatMap(p=>store.list('run',p.id)):store.list('run',scope));const reported=runs.filter(r=>r.accountedTokens!=null||r.usage?.total?.totalTokens!=null);const improvements=scope==='company'?[]:improvementCandidates(store,scope).map(i=>{const signals=dated(store.list('operationSignal',scope)).filter(s=>s.kind===i.kind&&s.topic===i.topic);const split=i.appliedAt;const before=signals.filter(s=>!split||s.createdAt<split),after=signals.filter(s=>split&&s.createdAt>=split);const completed=tasks.filter(t=>t.finishedAt&&inDate(localDate(t.finishedAt,zone)));return {...i,effect:{before:{events:before.length,completedTasks:completed.filter(t=>!split||t.finishedAt<split).length},after:split?{events:after.length,completedTasks:completed.filter(t=>t.finishedAt>=split).length}:null,period:range,conclusion:'관찰 건수입니다. 기간·업무량 차이가 있어 인과 효과는 아직 확인되지 않았습니다.'}};});
  return {experiment,period:range,observedThrough:today,knownMinutes:known?sum(entries):null,projectMinutes:own.some(e=>e.target==='project')?sum(own.filter(e=>e.target==='project')):null,toolMinutes:entries.some(e=>e.target==='company_tool')?sum(entries.filter(e=>e.target==='company_tool')):null,days,entries,coverage,taskCount:dated(tasks).length,acceptedGoals:accepted,verifiedGoals:goals.filter(g=>g.allVerified),goals,firstPass:ratio(firstIn.filter(r=>r.outcome==='accepted').length,firstIn.length),errorReopened:ratio(reopenedCohort.size,acceptedCohort.length),requirementsChanges:reopen.filter(r=>r.cause==='requirements_change').length,reworkMinutes:{error:entries.some(e=>e.cause==='error')?sum(entries.filter(e=>e.cause==='error')):null,requirements_change:entries.some(e=>e.cause==='requirements_change')?sum(entries.filter(e=>e.cause==='requirements_change')):null},autonomousProblems:{...ratio(problems.filter(p=>p.technicalIntervention==='none').length,problems.filter(p=>p.technicalIntervention!=='unknown').length),unknown:problems.filter(p=>p.technicalIntervention==='unknown').length,problems},usage:{turns:runs.length,tokens:reported.length?reported.reduce((n,r)=>n+(r.accountedTokens??r.usage.total.totalTokens),0):runs.length?null:0,unknown:runs.length-reported.length,cost:null,costBasis:'금액 미제공'},reviews,reopen,improvements,baseline:store.list('baseline',scope).filter(b=>inDate(b.date)).map(b=>{const g=goals.find(g=>g.id===b.goalId&&g.current);return {...b,comparisonNotes:[...(!g?['비교 목표 미연결']:[]),...(g&&normalize(g.acceptance)!==normalize(b.acceptance)?['완료 기준이 다름']:[]),'업무 종류·규모·모델·시점의 동일성은 대표 확인 필요'],comparable:false};}),measurementNote:'명시적으로 입력한 시간만 합산합니다. 미측정 시간을 0으로 보지 않습니다. 필수 승인 대기는 자율 처리 실패에 포함하지 않습니다.'};
}
