import React, { useState } from 'react';

export const categoryNames:Record<string,string>={bugfix:'오류 수정',documentation:'문서 정리',ui:'화면 개선',database:'DB 변경',requirements:'요구사항 구체화',marketing:'마케팅 분석',accounting:'회계 분석',hr:'인사·채용 제안',feature:'새 기능',direction:'사업 방향',external_send:'외부 발송',spend:'지출',deploy:'서비스 배포',delete_data:'운영 데이터 삭제',permissions:'권한 확대'};
export const taskStates:Record<string,string>={queued:'대기',running:'실행 중',waiting_info:'정보 대기',waiting_approval:'승인 대기',paused:'일시정지',review:'검토 대기',completed:'완료',failed:'실패',cancelled:'취소',blocked:'확인 필요'};
type Objective={id:string;text:string;acceptance:string;priority:number};
type Policy={objectives:Objective[];scope:string;allowedCategories:string[];maxConcurrent:number;maxRetries:number;taskMinutes:number;turnMinutes:number;maxTaskCalls:number;sessionMinutes:number;checkMinutes:number;maxTasksPerPlan:number;maxMessageHops:number};
export type OperationTask={id:string;title:string;status:string;stage:string;reason?:string;error?:string;assignedEmployeeId?:string;priority?:number;materials?:string[];implementation?:string;verification?:string;deployment?:string};
type Brief={id:string;title:string;reason?:string};
type Decision={id:string;taskId:string;type:string;reason:string;options:string[];status:string;response?:string};
export type OperationsData={materials?:{id:string;title:string;text:string;source:string}[];decisions?:Decision[];operation?:{policy:Policy;state:string;reason:string;runner?:{online:boolean;pid:number;heartbeat:string};completed:Brief[];failed:Brief[];waiting:Brief[];next:Brief[];active:Brief[];lastPlan?:{summary:string;evidence:string[];runId:string}}};
type Project={id:string;name:string;maxRuns:number;tokenBudget:number|null;allowedPaths:string[];operationRevision?:number;model:string};
type Props={project?:Project;data:OperationsData&{tasks:OperationTask[];usage:{runs:number;tokens:number;unknown:number}};employees:{id:string;name:string;role:string}[];busy:boolean;act:(work:()=>Promise<unknown>,success?:string)=>Promise<void>;api:(url:string,method?:string,body?:unknown)=>Promise<unknown>;openTask:(id:string)=>void};

export function Autonomy({project,data,employees,busy,act,api,openTask}:Props){
  const [confirm,setConfirm]=useState(false);const [editing,setEditing]=useState(false);
  if(!project||!data.operation)return <section className="panel"><h2>프로젝트를 선택하세요</h2><p>직원은 회사에서 공유하고 자율 운영 목표와 한도는 프로젝트마다 설정합니다.</p></section>;
  const p=project,op=data.operation,policy=op.policy,base=`/scopes/${p.id}`;
  const list=(title:string,items:Brief[])=><section className="panel"><h3>{title} · {items.length}</h3>{items.length?items.map(t=><div className="operation-item" key={t.id}><button className="text-button" onClick={()=>openTask(t.id)}>{t.title}</button>{t.reason&&<p>{t.reason}</p>}</div>):<p className="subtle">없음</p>}</section>;
  return <div className="autonomy">
    <section className="panel operation-hero"><div><span className="eyebrow">AUTONOMOUS OPERATIONS</span><h2>{p.name} 운영실</h2><p>{op.reason}</p><span className={`badge ${op.state}`}>{taskStates[op.state]||({waiting:'대기',online:'켜짐'} as Record<string,string>)[op.state]||op.state}</span></div><div className="operation-controls"><span className="subtle">실행기 {op.runner?.online?'연결됨':'꺼짐 · npm run runner 실행 필요'}</span><button className="primary" disabled={busy} onClick={()=>setConfirm(true)}>시작 / 재개 범위 확인</button><button disabled={busy} onClick={()=>act(()=>api(base+'/operation/pause','POST'))}>이 프로젝트 일시정지</button></div></section>
    {confirm&&<section className="panel operation-confirm" role="region" aria-label="자율 운영 시작 확인"><h3>이 범위로 자율 운영을 시작합니다</h3><p><strong>{p.name}</strong> · 모델 {p.model||'Codex 기본 모델'}</p><ul>{policy.objectives.map(g=><li key={g.id}>우선순위 {g.priority} · {g.text}<br/><span className="subtle">완료 기준: {g.acceptance}</span></li>)}</ul><p>허용 범위: {policy.scope||'설정 필요'}</p><p>업무 분류: {policy.allowedCategories.map(c=>categoryNames[c]).join(', ')}</p><p>변경 경로: {p.allowedPaths.join(', ')}</p><p>동시 {policy.maxConcurrent}건 · 수정 재시도 {policy.maxRetries}회 · 업무당 {policy.maxTaskCalls}호출 / {policy.taskMinutes}분 · 턴당 {policy.turnMinutes}분</p><p>운영 {policy.sessionMinutes}분 · 프로젝트 누적 {p.maxRuns}호출 / {p.tokenBudget==null?'무제한':p.tokenBudget.toLocaleString()}토큰</p><p className="field-help">외부 발송·지출·배포·운영 삭제·권한 확대는 자동 실행하지 않고 결정함에 남깁니다. 실행기가 켜져 있어야 업무가 이어집니다.</p><div className="candidate-actions"><button className="primary" disabled={busy||!policy.objectives.length||!policy.scope.trim()} onClick={()=>act(async()=>{await api(base+'/operation/start','POST',{revision:p.operationRevision||0});setConfirm(false);},'자율 운영을 시작했습니다.')}>확인한 범위로 시작</button><button onClick={()=>setConfirm(false)}>닫기</button></div></section>}
    <div className="stats"><section className="stat"><div>모델 호출</div><strong>{data.usage.runs}<small>/ {p.maxRuns}</small></strong><p>실패·중단 시도 포함</p></section><section className="stat"><div>보고된 토큰</div><strong>{data.usage.tokens.toLocaleString()}</strong><p>누적 한도 {p.tokenBudget==null?'무제한':p.tokenBudget.toLocaleString()}</p></section><section className="stat"><div>요금</div><strong>미제공</strong><p>추정 금액을 표시하지 않습니다</p></section><section className="stat"><div>사용량 미확인</div><strong>{data.usage.unknown}<small>회</small></strong><p>호출 수에는 포함됩니다</p></section></div>
    <section className="panel"><div className="section-head"><h2>운영 목표와 범위</h2><button onClick={()=>setEditing(!editing)}>{editing?'편집 닫기':'목표·한도 설정'}</button></div>{policy.objectives.length?policy.objectives.map(g=><div className="operation-item" key={g.id}><strong>{g.priority}. {g.text}</strong><p>{g.acceptance}</p></div>):<p>목표와 완료 기준을 먼저 등록하세요.</p>}{editing&&<PolicyForm key={p.id+':'+p.operationRevision} policy={policy} busy={busy} save={value=>act(async()=>{await api(base+'/operation','PUT',value);setEditing(false);},'운영 설정을 저장했습니다. 시작 전에 적용 범위를 확인하세요.')}/>}</section>
    <div className="operation-grid">{list('실제 완료 · 검토 대기 포함',op.completed)}{list('실패',op.failed)}{list('막힌 업무',op.waiting)}{list('다음 진행할 업무',op.next)}</div>
    <section className="panel"><h2>직원별 현재 업무</h2>{employees.map(e=>{const assigned=data.tasks.filter(t=>t.assignedEmployeeId===e.id&&t.status==='running');return <div className="operation-item" key={e.id}><strong>{e.name} · {e.role}</strong><p>{assigned.length?assigned.map(t=>t.title).join(', '):'호출 대기'}</p></div>})}{!employees.length&&<p>회사에서 채용한 직원을 프로젝트에 배정하세요.</p>}</section>
    {op.lastPlan&&<section className="panel"><h2>PO의 최근 운영 판단</h2><p>{op.lastPlan.summary}</p><p className="field-help">확인 자료: {op.lastPlan.evidence.join(', ')} · 실행 {op.lastPlan.runId}</p></section>}
    <section className="panel"><h2>대표 결정함</h2>{data.decisions?.filter(d=>d.status==='pending').map(d=><DecisionCard key={d.id} decision={d} busy={busy} open={()=>openTask(d.taskId)} resolve={(action,response)=>act(()=>api(base+'/decisions/'+encodeURIComponent(d.id)+'/resolve','POST',{action,response}))}/>)}{!data.decisions?.some(d=>d.status==='pending')&&<p className="subtle">지금 결정할 항목이 없습니다.</p>}
      {data.decisions?.filter(d=>d.status!=='pending').map(d=><details key={d.id}><summary>{d.status==='approved'?'승인':'거절'} · {d.reason.slice(0,60)}</summary><p>{d.response}</p></details>)}
    </section>
    <section className="panel"><h2>정보를 기다리는 업무</h2>{data.tasks.filter(t=>t.status==='waiting_info').map(t=><form key={t.id} className="operation-item" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);act(()=>api(base+'/tasks/'+encodeURIComponent(t.id)+'/respond','POST',{response:f.get('response'),materials:f.getAll('materials')}));}}><button type="button" className="text-button" onClick={()=>openTask(t.id)}>{t.title}</button><p>{t.reason||t.error}</p><label>추가 정보<textarea name="response" required/></label><label>연결할 실제 자료<select multiple name="materials" defaultValue={t.materials||[]}>{data.materials?.map(m=><option key={m.id} value={m.id}>{m.title}</option>)}</select></label><button disabled={busy}>정보 전달하고 다시 검토</button></form>)}{!data.tasks.some(t=>t.status==='waiting_info')&&<p className="subtle">없음</p>}</section>
    <section className="panel"><h2>프로젝트 자료함</h2><p className="field-help">고객 피드백·회계 내역·정책 등 실제 자료를 입력하세요. 이 프로젝트 직원만 실행 맥락에 받습니다.</p><form onSubmit={e=>{e.preventDefault();const form=e.currentTarget;act(async()=>{await api(base+'/materials','POST',Object.fromEntries(new FormData(form)));form.reset();});}}><div className="form-row"><label>자료 이름<input name="title" required/></label><label>자료 출처<input name="source" required placeholder="예: 대표가 확인한 9월 피드백"/></label></div><label>자료 내용<textarea name="text" required rows={4}/></label><button disabled={busy}>자료 저장</button></form>{data.materials?.map(m=><details key={m.id}><summary>{m.title} · {m.source}</summary><p className="message-text">{m.text}</p><code>{m.id}</code></details>)}</section>
  </div>;
}

function PolicyForm({policy,busy,save}:{policy:Policy;busy:boolean;save:(p:Policy)=>void}){
  const [goals,setGoals]=useState<Objective[]>(policy.objectives.length?policy.objectives:[{id:crypto.randomUUID(),text:'',acceptance:'',priority:1}]);
  const [allowed,setAllowed]=useState(policy.allowedCategories);
  const numeric:[keyof Policy,string,number,number][]=[['maxConcurrent','프로젝트 동시 업무 수',1,4],['maxRetries','수정·실행 재시도 한도',0,5],['taskMinutes','업무 누적 실행 시간(분)',1,240],['turnMinutes','직원 1회 실행 시간(분)',1,30],['maxTaskCalls','업무 모델 호출 한도',1,100],['sessionMinutes','이번 운영 시간(분)',1,1440],['checkMinutes','정기 점검 간격(분)',1,1440],['maxTasksPerPlan','PO 계획당 업무 수',1,10],['maxMessageHops','동료 질문 연쇄 한도',1,20]];
  return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const p={...policy,scope:String(f.get('scope')),objectives:goals,allowedCategories:allowed};numeric.forEach(([key])=>Object.assign(p,{[key]:Number(f.get(key))}));save(p);}}>
    {goals.map((g,i)=><div className="goal-editor" key={g.id}><label>운영 목표 {i+1}<input required value={g.text} onChange={e=>setGoals(goals.map(x=>x.id===g.id?{...x,text:e.target.value}:x))}/></label><label>검증 가능한 완료 기준<textarea required value={g.acceptance} onChange={e=>setGoals(goals.map(x=>x.id===g.id?{...x,acceptance:e.target.value}:x))}/></label><label>우선순위 · 1이 가장 높음<input type="number" min="1" max="5" required value={g.priority} onChange={e=>setGoals(goals.map(x=>x.id===g.id?{...x,priority:Number(e.target.value)}:x))}/></label><button type="button" onClick={()=>setGoals(goals.filter(x=>x.id!==g.id))}>목표 제거</button></div>)}
    <button type="button" onClick={()=>setGoals([...goals,{id:crypto.randomUUID(),text:'',acceptance:'',priority:3}])}>목표 추가</button><label>사전에 허용하는 업무 범위<textarea name="scope" required defaultValue={policy.scope} rows={4} placeholder="예: 기존 인사 기능의 공백 처리 오류 수정과 회귀 테스트. 새로운 기능·가격 정책은 제안만."/></label>
    <div className="category-options">{Object.entries(categoryNames).filter(([id])=>!['external_send','spend','deploy','delete_data','permissions'].includes(id)).map(([id,name])=><label className="check-label" key={id}><input type="checkbox" checked={allowed.includes(id)} onChange={e=>setAllowed(e.target.checked?[...allowed,id]:allowed.filter(x=>x!==id))}/>{name}</label>)}</div>
    <div className="form-row">{numeric.map(([key,label,min,max])=><label key={key}>{label}<input name={key} type="number" min={min} max={max} defaultValue={Number(policy[key])} required/></label>)}</div><p className="field-help">토큰은 알림 수신 시 중단하므로 마지막 호출이 한도를 넘을 수 있습니다. 호출 수와 실행 시간도 함께 제한합니다. 프로젝트·회사 누적 예산은 프로젝트 설정과 운영 설정에서 관리합니다.</p><button className="primary" disabled={busy}>목표와 한도 저장</button>
  </form>;
}
function DecisionCard({decision:d,busy,open,resolve}:{decision:Decision;busy:boolean;open:()=>void;resolve:(action:string,response:string)=>void}){
  const [response,setResponse]=useState('');return <article className="decision-card"><button className="text-button" onClick={open}>관련 업무와 결과 보기</button><p className="message-text">{d.reason}</p><ul>{d.options.map(x=><li key={x}>{x}</li>)}</ul><label>결정 이유 / 구체적인 허용 범위<textarea value={response} onChange={e=>setResponse(e.target.value)}/></label><div className="candidate-actions"><button className="primary" disabled={busy||!response.trim()} onClick={()=>resolve('approve',response)}>승인 기록</button><button disabled={busy||!response.trim()} onClick={()=>resolve('reject',response)}>거절 · 업무 취소</button></div></article>;
}
export function TaskBoard({tasks,busy,openTask,run,cancel}:{tasks:OperationTask[];busy:boolean;openTask:(id:string)=>void;run:(id:string)=>void;cancel:(id:string)=>void}){
  return <div className="autonomous-board">{Object.entries(taskStates).filter(([s])=>s!=='blocked').map(([status,name])=><section className="board-column" key={status}><div className="column-head"><h2>{name}</h2><small>{tasks.filter(t=>t.status===status).length}</small></div>{tasks.filter(t=>t.status===status).map(t=><article className="task-card" key={t.id}><small>우선순위 {t.priority||3} · {t.stage}</small><button className="task-title" onClick={()=>openTask(t.id)}>{t.title}</button><p>{t.reason||t.error}</p><p>구현 {t.implementation==='complete'?'완료':'대기'} · 검증 {t.verification==='passed'?'통과':'대기'} · 배포 {t.deployment==='deployed'?'완료':'미배포'}</p>{['queued','paused'].includes(t.status)&&<button disabled={busy} onClick={()=>run(t.id)}>실행 요청</button>}{!['completed','review','cancelled','failed'].includes(t.status)&&<button disabled={busy} onClick={()=>cancel(t.id)}>취소</button>}</article>)}{!tasks.some(t=>t.status===status)&&<p className="board-empty">업무 없음</p>}</section>)}</div>;
}
