import React,{useEffect,useState} from 'react';
import {taskStates} from './Autonomy';

type Row=Record<string,any>;
const names:Record<string,string>={briefing:'목표 설명·업무 지시',decision:'질문·의사결정',review:'결과물 검토',editing:'직접 코드·문서 수정',recovery:'오류·장애 수습',maintenance:'앱 설정·유지보수'};
const minutes=(n:number|null|undefined)=>n==null?'미측정':`${Math.round(n*10)/10}분`;
const ratio=(r:Row)=>`${r.value==null?'미측정':Math.round(r.value*100)+'%'} (${r.numerator}/${r.denominator})`;
const roleNames:Record<string,string>={po:'사업 PO',cto:'CTO',backend:'백엔드',frontend:'프런트엔드',qa:'QA',planner:'기획자',marketer:'마케터',designer:'디자이너',database:'DB 엔지니어',accountant:'회계 담당',hr:'인사 담당'};
const day=()=>new Intl.DateTimeFormat('sv-SE',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
const fields=(form:HTMLFormElement)=>Object.fromEntries(new FormData(form));
async function request(url:string,method='GET',body?:unknown){const r=await fetch('/api'+url,{method,headers:body?{'Content-Type':'application/json'}:undefined,body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.error);return d;}
export function Personal({scope,openTask,openRun,openChat,openExperience,navigate}:{scope:string;openTask:(id:string)=>void;openRun:(id:string)=>void;openChat:(employeeId:string,channel?:string)=>void;openExperience:(employeeId:string)=>void;navigate:(page:string)=>void}){
  const [data,setData]=useState<Row>(),[tab,setTab]=useState('desk'),[error,setError]=useState(''),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  const base=`/scopes/${scope}/personal`,project=scope!=='company';
  const refresh=async()=>setData(await request(base));
  useEffect(()=>{let alive=true;const load=()=>request(base).then(d=>{if(alive)setData(d);}).catch(e=>{if(alive)setError(e.message);});load();const timer=setInterval(load,3000);return()=>{alive=false;clearInterval(timer);};},[base]);
  const act=async(path:string,body?:unknown,method='POST')=>{setBusy(true);setError('');try{const result=await request(base+path,method,body);await refresh();setNotice('저장했습니다.');return result;}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const form=(run:(f:Row,el:HTMLFormElement)=>void)=>(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();run(fields(e.currentTarget),e.currentTarget);};
  if(!data)return <p role="status">대표 화면을 불러오고 있습니다.</p>;
  const m=data.metrics,goals=m.goals||[],tasks:Row[]=data.tasks,people:Row[]=data.employees;
  const taskLink=(id:string,title?:string)=><button type="button" className="text-button" onClick={()=>openTask(id)}>{title||tasks.find(t=>t.id===id)?.title||'업무 근거'}</button>;
  const blocked=tasks.filter(t=>['waiting_info','waiting_approval','failed','paused'].includes(t.status));
  const next=tasks.filter(t=>t.status==='queued');
  const results=tasks.filter(t=>t.evidence&&['review','completed','reopened'].includes(t.status)).slice().sort((a,b)=>String(b.finishedAt||b.createdAt).localeCompare(String(a.finishedAt||a.createdAt)));
  return <div className="personal"><div className="personal-tabs" role="navigation" aria-label="대표 화면 메뉴">{[['desk','오늘 확인'],['goals','목표·성과'],['time','내 시간'],['collaboration','회의·개선'],['experiment','관찰 설정']].map(([id,title])=><button className={tab===id?'selected':''} key={id} onClick={()=>setTab(id)}>{title}</button>)}</div>
    {error&&<p className="alert error" role="alert">{error}</p>}{notice&&<p role="status" className="subtle">{notice}</p>}
    <p className="subtle">관찰 기간 {m.period.start} ~ {m.period.end} · {m.experiment?.label||'관찰 기간 미설정'} · {m.measurementNote}</p>
    {data.notifications.length>0&&<section className="alert" aria-live="polite"><div><strong>설정한 긴급 조건에 해당하는 요청</strong>{data.notifications.map((n:Row)=><p key={n.id}>{n.text} <button onClick={()=>act('/notifications/'+encodeURIComponent(n.id)+'/read',{})}>확인 표시</button></p>)}</div></section>}
    {tab==='desk'&&<>
      <div className="personal-metrics"><article className="panel"><small>대표의 기록된 전체 부담</small><h2>{minutes(m.knownMinutes)}</h2><p>프로젝트 {minutes(m.projectMinutes)} · 도구 관리 {minutes(m.toolMinutes)}</p><button onClick={()=>setTab('time')}>시간 기록</button></article><article className="panel"><small>완료 기준을 확인한 기능·개선</small><h2>{m.acceptedGoals.length}개</h2><p>Task {m.taskCount}개와 구분 · 목표 기준 버전별 집계</p><button onClick={()=>setTab('goals')}>근거 확인</button></article><article className="panel"><small>이 관찰 기간 모델 사용량</small><h2>{m.usage.turns}회</h2><p>{m.usage.tokens==null?'토큰 미측정':m.usage.tokens.toLocaleString()+' tokens'} · 비용 미제공</p><small>사용량 미확인 {m.usage.unknown}회 · 현재 프로젝트 누적 {data.usage.tokens.toLocaleString()} tokens</small></article></div>
      {!project&&<section className="panel"><h2>프로젝트를 선택하면 목표·결정·결과를 모아 볼 수 있습니다.</h2><p>회사 공통에서는 회사 전체의 기록된 시간과 도구 관리 시간을 확인합니다.</p><button onClick={()=>navigate('projects')}>프로젝트 연결·선택</button></section>}
      <section className="panel"><h2>내가 결정할 사항 <span className="count">{data.inbox.length}</span></h2><p className="subtle">긴급 요청은 즉시 이 화면 상단에 표시합니다. 나머지는 이 확인함에서 함께 봅니다. 묶음 확인 시각: {data.settings.digestHour??18}시 · 외부 알림은 연결되지 않았습니다.</p>{data.inbox.length===0?<p>현재 대표 답변을 기다리는 결정이 없습니다.</p>:data.inbox.map((d:Row)=><article className="personal-item" key={d.id}><h3>{d.urgent?'긴급 · ':''}{d.question}</h3><p>{d.why}</p><p><strong>추천:</strong> {d.recommendation} — {d.recommendationReason}</p><p>다른 선택지: {d.alternatives.join(' / ')}</p><p>같은 요청 {d.occurrences}건 · {d.preplannedApproval?'사전에 정한 승인 대상':'대표 판단 필요'}</p><div>답변이 없으면 영향받는 업무: {d.affectedTasks.map((t:Row)=><span key={t.id}>{taskLink(t.id,t.title)} </span>)}</div><div>기다리는 동안 진행 가능한 업무: {d.canContinue.length?d.canContinue.map((t:Row)=><span key={t.id}>{taskLink(t.id,t.title)} </span>):'현재 없음'}</div><form onSubmit={form(f=>act('/decisions/'+d.id,{action:f.action,response:f.response}))}><label>답변과 결정 이유<textarea required name="response"/></label><label>결정<select name="action"><option value="approve">답변 반영·승인</option><option value="reject">보류 없이 해당 업무 취소</option></select></label><button disabled={busy}>묶인 {d.occurrences}건에 답변</button></form></article>)}</section>
      <section className="panel"><h2>최근 제출된 검증 결과</h2>{results.length===0?<p>검증 근거가 준비된 결과가 없습니다.</p>:results.slice(0,8).map(t=><article className="personal-item" key={t.id}><h3>{taskLink(t.id,t.title)}</h3><p>{taskStates[t.status]||t.status} · 검증 {t.verification} · 배포 {t.deployment==='deployed'?'완료':'미실행'}</p><p>변경 파일: {t.result?.files?.join(', ')||'산출물 기록 확인'}</p><a href={`/api/scopes/${scope}/tasks/${t.id}/evidence`}>검증 근거 다운로드</a> <button onClick={()=>openChat('')}>관련 대화</button>{['review','completed'].includes(t.status)&&<form onSubmit={form(f=>act('/results/'+t.id,f))}><div className="form-row"><label>대표 검토<select name="outcome"><option value="accepted">그대로 수용</option><option value="changes">수정 요청</option></select></label><label>수정 이유<select name="cause"><option value="none">수정 없음</option><option value="error">오류 수정</option><option value="requirements_change">요구사항 변경</option></select></label><label>대표 기술 개입<select name="technicalIntervention"><option value="unknown">미측정·모름</option><option value="none">기술 개입 없이 해결 확인</option><option value="yes">직접 기술적으로 개입</option></select></label></div><label>피드백·판단 근거<textarea name="notes"/></label><button disabled={busy}>검토 기록 저장</button></form>}</article>)}</section>
      <div className="personal-grid"><section className="panel"><h2>막힌 업무와 원인</h2>{blocked.length?blocked.map(t=><p key={t.id}>{taskLink(t.id,t.title)}<br/>{taskStates[t.status]||t.status} · {t.reason||t.error}</p>):<p>막힌 업무 없음</p>}</section><section className="panel"><h2>다음에 진행할 업무</h2>{next.length?next.map(t=><p key={t.id}>{taskLink(t.id,t.title)} · 우선순위 {t.priority}</p>):<p>진행할 일이 없어 대기합니다.</p>}{data.stopped&&<p>전체 중지 중입니다. 대기 업무는 실행되지 않습니다.</p>}<button onClick={()=>navigate('autonomy')}>운영 범위·한도 확인</button></section></div>
      <section className="panel"><h2>사무실 · 실제 업무 상태</h2><div className="personal-grid">{people.map(e=><article key={e.id}><h3>{e.name} · {roleNames[e.role]||e.role}</h3><p>{e.coordinator?'대표 창구 ':''}{e.technicalCoordinator?'기술 조율':''}</p>{e.tasks.length?e.tasks.map((t:Row)=><p key={t.id}>{taskLink(t.id,t.title)} · {taskStates[t.status]||t.status} / {t.stage}</p>):<p>현재 배정 업무 없음</p>}<button onClick={()=>openChat(e.id)}>직접 대화</button> <button onClick={()=>openExperience(e.id)}>경력 근거</button></article>)}</div></section>
    </>}
    {tab==='goals'&&<>
      {project&&<section className="panel"><h2>PO에게 목표 맡기기</h2><form onSubmit={form(f=>act('/goals',{...f,priority:Number(f.priority)}))}><label>목표<textarea name="text" required/></label><label>사전에 정한 완료 기준<textarea name="acceptance" required/></label><div className="form-row"><label>우선순위<input name="priority" type="number" min="1" max="5" defaultValue="1" required/></label><label>업무 종류<input name="taskType" defaultValue="기능 개선" required/></label><label>규모<select name="size"><option value="small">작음</option><option value="medium">중간</option><option value="large">큼</option></select></label></div><button disabled={busy}>목표 저장</button> <button type="button" onClick={()=>navigate('autonomy')}>적용 범위·한도 확인 후 시작</button><p className="field-help">새 목표는 자동 승인되지 않습니다. 자율 운영에서 적용 범위를 확인하면 PO가 실제 자료로 업무를 나눕니다.</p></form></section>}
      <section className="panel"><h2>의미 있는 결과와 품질</h2><p>첫 검토 수용률: {ratio(m.firstPass)} · 오류로 다시 열린 비율: {ratio(m.errorReopened)}</p><p>기술 개입 없이 해결한 문제: {ratio(m.autonomousProblems)} · 개입 여부 미측정 {m.autonomousProblems.unknown}건</p><p>요구사항 변경 {m.requirementsChanges}건 · 오류 재작업 {minutes(m.reworkMinutes.error)} · 요구사항 추가 작업 {minutes(m.reworkMinutes.requirements_change)}</p><p className="subtle">오류 재개 비율의 분모는 이 기간 처음 수용한 업무입니다. 사전 필수 승인은 자율 처리 실패로 계산하지 않습니다. 30분 목표 달성 여부는 시간 기록의 누락을 확인한 뒤 판단하세요.</p>{m.reviews.map((r:Row)=><p key={r.id}>{taskLink(r.taskId)} · {r.outcome==='accepted'?'수용':'수정 요청'} · {r.notes||'추가 설명 없음'}</p>)}{goals.map((g:Row)=><article key={g.id+g.version} className="personal-item"><h3>{g.text} · 기준 v{g.version}{g.current?'':' (과거 버전)'}</h3><p>{g.acceptance}</p><p>{g.accepted?'완료 기준 충족 확인':g.allVerified?'연결 결과 검증 통과 · 대표의 목표 확인 대기':'진행 중 또는 검증 대기'}</p>{g.tasks.map((t:Row)=><p key={t.id}>{taskLink(t.id,t.title)} · {taskStates[t.status]||t.status}{t.teamPlan&&<small> · 담당 {people.find(e=>e.id===t.teamPlan.ownerId)?.name} · 검토 {t.teamPlan.reviewerIds.map((id:string)=>people.find(e=>e.id===id)?.name).join(', ')}</small>}</p>)}{!g.accepted&&<form onSubmit={form(f=>act('/goals/'+g.id+'/assess',{version:g.version,notes:f.notes}))}><label>완료 기준 확인 근거<textarea name="notes" required/></label><button disabled={busy||!g.allVerified}>기능·개선 완료 기준 충족 확인</button></form>}</article>)}</section>
    </>}
    {tab==='time'&&<>
      <section className="panel"><h2>내 개입 시간</h2><p>창을 열어 둔 시간은 자동 집계하지 않습니다. 시작한 타이머는 명시적으로 종료할 때 기록됩니다. 자리를 비웠다면 종료할 때 실제 시간을 조정하세요.</p><p>현재 타이머: {data.timer?.status==='running'?`${names[data.timer.category]} · ${new Date(data.timer.startedAt).toLocaleString()}부터`:data.timer?.status==='other_scope'?'다른 범위에서 실행 중':'정지'}</p>{data.timer?.status==='running'?<form onSubmit={form(f=>act('/timer/stop',{...(f.minutes!==''?{minutes:Number(f.minutes)}:{}),note:f.note}))}><label>실제로 개입한 시간으로 조정 (비워 두면 타이머 시간)<input type="number" name="minutes" min="0" step="0.1"/></label><label>메모<input name="note" defaultValue={data.timer.note}/></label><button disabled={busy}>종료·시간 저장</button></form>:<TimeForm tasks={tasks} goals={goals} project={project} busy={busy||data.timer?.status==='other_scope'} timer submit={f=>act('/timer/start',f)}/>}
      <h3>사후 시간 입력</h3><TimeForm tasks={tasks} goals={goals} project={project} busy={busy} submit={f=>act('/time',f)}/></section>
      <section className="panel"><h2>하루 {m.experiment?.targetMinutes||30}분 목표 · 제한이 아닌 관찰</h2><p>합계 {minutes(m.knownMinutes)} / 프로젝트 {minutes(m.projectMinutes)} / 도구 관리 {minutes(m.toolMinutes)}</p><div className="personal-table"><table><thead><tr><th>날짜</th><th>기록한 시간</th><th>목표 초과</th><th>활동별 내역</th><th>측정 상태</th></tr></thead><tbody>{m.days.map((d:Row)=><tr key={d.date}><td>{d.date}</td><td>{minutes(d.measuredMinutes)}</td><td>{minutes(d.overTarget)}</td><td>{Object.entries(d.categories).map(([id,n])=><div key={id}>{names[id]} {minutes(n as number|null)}</div>)}</td><td>{d.coverageComplete?'모든 개입을 기록했다고 확인함':'누락 여부 미확인'}{d.date<=day()&&<button disabled={busy} onClick={()=>act('/coverage',{date:d.date,complete:!d.coverageComplete})}>{d.coverageComplete?'확인 취소':'이 날짜 모두 기록함'}</button>}</td></tr>)}</tbody></table></div><h3>원본 기록</h3>{m.entries.map((e:Row)=><p key={e.id}>{e.date} · {names[e.category]} · {e.target==='company_tool'?'도구 관리':'프로젝트'} · {minutes(e.minutes)} · {e.note} {e.taskId&&e.projectId===scope&&taskLink(e.taskId)}{e.projectId===scope&&<button onClick={()=>{const reason=window.prompt('기록 취소 이유 (원본은 남습니다)');if(reason)act('/time/'+e.id+'/void',{reason});}}>기록 취소</button>}</p>)}</section>
    </>}
    {tab==='collaboration'&&project&&<>
      <section className="panel"><h2>안건이 있는 회의</h2><form onSubmit={form((f,el)=>act('/meetings',{agenda:f.agenda,taskId:f.taskId,participantIds:new FormData(el).getAll('participantIds')}))}><label>해결할 안건<textarea name="agenda" required/></label><label>관련 업무<select name="taskId"><option value="">목표·운영 조율</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><fieldset><legend>필요한 직원만 선택</legend>{people.map(e=><label key={e.id}><input type="checkbox" name="participantIds" value={e.id}/>{e.name} · {e.role}</label>)}</fieldset><button disabled={busy}>회의 안건 저장</button></form>{data.meetings.map((mt:Row)=><article className="personal-item" key={mt.id}><h3>{mt.agenda}</h3><p>{mt.status==='draft'?'실행 전':mt.status==='open'?'회의 중':'정리 완료'}</p><button onClick={()=>openChat('',`meeting-${mt.id}`)}>회의 대화·참여</button>{mt.status==='draft'&&<button disabled={busy||data.stopped} onClick={()=>act('/meetings/'+mt.id+'/start',{})}>선택한 {mt.participantIds.length}명에게 안건 전달</button>}{mt.status==='open'&&<form onSubmit={form(f=>act('/meetings/'+mt.id+'/close',{decisions:f.decisions,actions:f.taskId?[{taskId:f.taskId,employeeId:f.employeeId,responsibility:f.responsibility}]:[]}))}><label>결정사항<textarea required name="decisions"/></label><label>담당 업무 연결<select name="taskId"><option value="">후속 업무 없음</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label>담당 직원<select name="employeeId">{people.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>책임·다음 행동<input name="responsibility"/></label><button disabled={busy}>회의 결과 정리</button></form>}{mt.decisions&&<p>{mt.decisions}</p>}{mt.actions?.map((a:Row,i:number)=><p key={i}>{taskLink(a.taskId)} · {people.find(e=>e.id===a.employeeId)?.name}: {a.responsibility}</p>)}</article>)}</section>
      <section className="panel"><h2>반복 질문·오류에서 운영 개선</h2><form onSubmit={form(f=>act('/signals',f))}><label>기록 종류<select name="kind"><option value="question">반복 질문</option><option value="recovery">오류 수습</option><option value="feedback">대표 피드백</option></select></label><label>실제로 있었던 내용<textarea name="text" required/></label><button disabled={busy}>근거 기록</button></form><p className="subtle">같은 종류와 내용의 기록이 2회 이상이면 후보가 생깁니다. 적용은 대표가 결정하고 이 프로젝트 안에서만 사용합니다.</p>{m.improvements.map((i:Row)=><article className="personal-item" key={i.id}><h3>{i.title} · v{i.version} / {i.status}</h3><p>근거 {i.sourceIds.length}건 · 적용 전 {i.effect.before.events}회 / 완료 업무 {i.effect.before.completedTasks}개 · 적용 후 {i.effect.after?`${i.effect.after.events}회 / 완료 업무 ${i.effect.after.completedTasks}개`:'미측정'}</p><p>{i.effect.conclusion}</p><details><summary>근거 기록</summary>{data.signals.filter((s:Row)=>i.sourceIds.includes(s.id)).map((s:Row)=><p key={s.id}>{s.createdAt}: {s.text} {s.taskId&&taskLink(s.taskId)} {s.runId&&<button onClick={()=>openRun(s.runId)}>실행</button>}</p>)}</details><form onSubmit={form(f=>act('/improvements/'+i.id,{...f,active:f.active==='true'},'PUT'))}><label>적용할 규칙<textarea name="rule" defaultValue={i.rule} required/></label><label>예상 효과와 확인 방법<textarea name="expectedEffect" defaultValue={i.expectedEffect} required/></label><label>적용 대상<select name="employeeId" defaultValue={i.employeeId||''}><option value="">이 프로젝트의 모든 직원</option>{people.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><label>상태<select name="active" defaultValue={String(i.status==='applied')}><option value="false">비활성화</option><option value="true">활성화</option></select></label><button disabled={busy}>새 버전 저장</button></form></article>)}</section>
    </>}
    {tab==='experiment'&&project&&<>
      <section className="panel"><h2>대표 창구와 긴급 조건</h2><form key={scope} onSubmit={form((f,el)=>act('/settings',{coordinatorId:f.coordinatorId,technicalCoordinatorId:f.technicalCoordinatorId,urgentTypes:new FormData(el).getAll('urgentTypes'),urgentKeywords:String(f.urgentKeywords).split('\n').map(x=>x.trim()).filter(Boolean),digestHour:Number(f.digestHour)},'PUT'))}><label>대표 창구<select name="coordinatorId" defaultValue={data.settings.coordinatorId||''}><option value="">기본 사업 PO</option>{people.map(e=><option key={e.id} value={e.id}>{e.name} · {e.role}</option>)}</select></label><label>기술 조율<select name="technicalCoordinatorId" defaultValue={data.settings.technicalCoordinatorId||''}><option value="">기본 CTO</option>{people.filter(e=>e.role==='cto').map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select></label><fieldset><legend>즉시 표시할 결정 종류</legend>{[['external','외부 작업 승인'],['conflict','해결되지 않은 충돌'],['scope','업무 범위 변경'],['info','정보 부족'],['failure','실행 실패']].map(([id,title])=><label key={id}><input type="checkbox" name="urgentTypes" value={id} defaultChecked={data.settings.urgentTypes?.includes(id)}/>{title}</label>)}</fieldset><label>긴급 키워드 (한 줄에 하나)<textarea name="urgentKeywords" defaultValue={data.settings.urgentKeywords?.join('\n')}/></label><label>묶어서 확인할 시각<input name="digestHour" type="number" min="0" max="23" defaultValue={data.settings.digestHour??18}/></label><button disabled={busy}>창구·알림 조건 저장</button></form></section>
      <section className="panel"><h2>첫 관찰 기간</h2><form onSubmit={form(f=>act('/experiment',{...f,days:Number(f.days),targetMinutes:Number(f.targetMinutes)}))}><label>실험 이름<input name="label" defaultValue="대표 하루 30분 운영 실험" required/></label><div className="form-row"><label>시작일<input type="date" name="startDate" defaultValue={day()} required/></label><label>관찰 기간<select name="days"><option value="7">1주</option><option value="14">2주</option></select></label><label>하루 개입 시간 목표 (분)<input type="number" name="targetMinutes" defaultValue="30" min="1" required/></label><label>날짜 기준<select name="timezone"><option value="Asia/Seoul">한국 시간</option><option value="UTC">UTC</option></select></label></div><button disabled={busy}>새 관찰 기간 설정</button></form><p>이전 실험과 기록은 보존합니다. 이 설정은 필요한 질문이나 검토를 생략하는 실행 한도가 아닙니다.</p></section>
      <section className="panel"><h2>기존 Codex 방식의 비교 기록</h2><form onSubmit={form(f=>act('/baseline',{...f,minutes:f.minutes===''?null:Number(f.minutes),tokens:f.tokens===''?null:Number(f.tokens),cost:f.cost===''?null:Number(f.cost)}))}><label>업무 이름<input name="title" required/></label><div className="form-row"><label>실행일<input name="date" type="date" defaultValue={day()} required/></label><label>종류<input name="taskType" required/></label><label>규모<select name="size"><option value="small">작음</option><option value="medium">중간</option><option value="large">큼</option></select></label></div><label>완료 기준<textarea name="acceptance" required/></label><label>비교할 목표<select name="goalId"><option value="">미연결</option>{goals.filter((g:Row)=>g.current).map((g:Row)=><option key={g.id} value={g.id}>{g.text}</option>)}</select></label><div className="form-row"><label>대표 소요 시간 (분)<input name="minutes" type="number" min="0" step="0.1"/></label><label>토큰<input name="tokens" type="number" min="0"/></label><label>비용<input name="cost" type="number" min="0" step="0.001"/></label><label>통화<select name="currency"><option>USD</option><option>KRW</option></select></label></div><label>비용 근거<select name="costBasis"><option value="unavailable">미측정</option><option value="measured">확인된 실제 비용</option><option value="estimated">추정 비용</option></select></label><label>사용 모델<input name="model"/></label><label>조건 차이와 메모<textarea name="notes"/></label><button disabled={busy}>비교 기록 저장</button><p>모르는 숫자는 비워 두세요. 0으로 채우지 않습니다.</p></form>{m.baseline.map((b:Row)=><article className="personal-item" key={b.id}><h3>{b.title}</h3><p>{b.taskType} · {b.size} · {b.date} · {minutes(b.minutes)}</p><p>완료 기준: {b.acceptance}</p><p>모델 {b.model||'미기록'} · 비용 {b.cost==null?'미측정':`${b.cost} ${b.currency} (${b.costBasis==='estimated'?'추정':'확인된 비용'})`}</p><p>{b.comparisonNotes.join(' · ')}</p></article>)}</section>
    </>}
    {!project&&['goals','collaboration','experiment'].includes(tab)&&<p className="panel">상단에서 프로젝트를 선택하세요. 이 기록은 프로젝트별로 보존됩니다.</p>}
  </div>;
}
function TimeForm({tasks,goals,project,busy,timer=false,submit}:{tasks:Row[];goals:Row[];project:boolean;busy:boolean;timer?:boolean;submit:(f:Row)=>unknown}){return <form onSubmit={e=>{e.preventDefault();const f=fields(e.currentTarget);submit({...f,...(!timer?{minutes:Number(f.minutes)}:{})});}}><div className="form-row"><label>활동<select name="category">{Object.entries(names).map(([id,label])=><option key={id} value={id}>{label}</option>)}</select></label><label>시간 구분<select name="target" defaultValue={project?'project':'company_tool'}>{project&&<option value="project">프로젝트 업무</option>}<option value="company_tool">AI 회사 도구 관리</option></select></label><label>발생 이유<select name="cause"><option value="normal">일반 작업</option><option value="error">오류에 따른 재작업</option><option value="requirements_change">요구사항 변경</option></select></label></div><div className="form-row"><label>관련 업무<select name="taskId"><option value="">미연결</option>{tasks.map(t=><option key={t.id} value={t.id}>{t.title}</option>)}</select></label><label>관련 목표<select name="goalId"><option value="">미연결</option>{goals.filter((g:Row)=>g.current).map((g:Row)=><option key={g.id} value={g.id}>{g.text}</option>)}</select></label></div>{!timer&&<div className="form-row"><label>날짜<input type="date" name="date" defaultValue={day()} required/></label><label>실제 개입 시간 (분)<input type="number" name="minutes" min="0" step="0.1" required/></label></div>}<label>메모<input name="note"/></label><button disabled={busy}>{timer?'타이머 시작':'사후 시간 저장'}</button></form>;}
